language: node_js
node_js: 12.13.0

env:
  - NODE_ENV=travis

install:
  - yarn install

jobs:
  include:
    - script: yarn lint
      name: Lint JavaScript
    - script: sleep 15; yarn test
      name: Tests
